full_path = r"C:\Users\jeanbaptiste\Desktop\chaipas"
path_image = "images/"
path_image_treatment = "images/treatment/"
path_blanck = "images/blanck/{}"
path_original_picture = "../images/" + "lign_v1.jpg"
